# Generated by Django 5.0.6 on 2024-05-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(choices=[('On loan', 'On loan'), ('Maintenance', 'Maintenance'), ('Reserved', 'Reserved')], default='Maintenance', max_length=20),
        ),
    ]
