# Generated by Django 5.0.6 on 2024-05-22 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_borrowinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowinghistory',
            name='book',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
            preserve_default=False,
        ),
    ]
