# Generated by Django 5.0.6 on 2024-05-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_bookinstance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowinghistory',
            name='returning_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
