# Generated by Django 5.0.6 on 2024-05-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_borrowinghistory_returning_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='borrowed_date',
            field=models.DateField(default='2020-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='returned_date',
            field=models.DateField(default='2020-01-01'),
            preserve_default=False,
        ),
    ]
