# Generated by Django 5.0.6 on 2024-05-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_bookinstance_borrowed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowinghistory',
            name='borrowing_date',
            field=models.DateTimeField(),
        ),
    ]
