# Generated by Django 5.0.6 on 2024-05-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_borrowinghistory_borrowing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='book_images/book cover.jpg', null=True, upload_to='book_images'),
        ),
    ]
