# Generated by Django 5.0.6 on 2024-05-24 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_borrowinghistory_borrowing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='book_images/2.jpg', null=True, upload_to='book_images'),
        ),
        migrations.AlterField(
            model_name='borrowinghistory',
            name='borrowing_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 24, 16, 48, 11, 382892, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
