# Generated by Django 5.0.6 on 2024-05-26 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_book_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'verbose_name': 'Book Instance', 'verbose_name_plural': 'Book Instances'},
        ),
        migrations.AlterModelOptions(
            name='borrowinghistory',
            options={'verbose_name': 'Borrowing History', 'verbose_name_plural': 'Borrowing Histories'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='books.genre', verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='book_images/2.jpg', null=True, upload_to='book_images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='stock_quantity',
            field=models.IntegerField(verbose_name='Stock Quantity'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='borrowed_date',
            field=models.DateField(verbose_name='Borrowed Date'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Borrower'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='returned_date',
            field=models.DateField(verbose_name='Returned Date'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(choices=[('On loan', 'On loan'), ('Maintenance', 'Maintenance'), ('Reserved', 'Reserved'), ('Returned', 'Returned')], default='On loan', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='borrowinghistory',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='borrowinghistory',
            name='book_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookinstance', verbose_name='Book Instance'),
        ),
        migrations.AlterField(
            model_name='borrowinghistory',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Borrower'),
        ),
        migrations.AlterField(
            model_name='borrowinghistory',
            name='borrowing_date',
            field=models.DateTimeField(verbose_name='Borrowing Date'),
        ),
        migrations.AlterField(
            model_name='borrowinghistory',
            name='returning_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Returning Date'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Expires At'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Reserved At'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
