# Generated by Django 5.0.6 on 2024-05-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowinghistory',
            name='late_return',
            field=models.BooleanField(default=False, verbose_name='Late Return'),
        ),
    ]
